const SUPABASE_URL = 'https://oxmaqeuhdggpmvxatxzk.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94bWFxZXVoZGdncG12eGF0eHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NDcyMTAsImV4cCI6MjA4ODEyMzIxMH0.uASYH1AyKKRVDuf2on2sMQ8A2S2lnM9ToDcuJBBtPvc';
const PARENT_PASSWORD = 'stars26';